module.exports.descriptors = [
  "Picnic Date",
  "Walk Date",
  "Elegant Date",
  "Dance Date",
  "Impromptu Date",
  "Movie Date",
  "Double Date",
  "Compassion Date",
  "Candle-light dinner Date",
  "Special Moment Date",
  "Make-up Date",
  "Lunch Date",
  "Old love Date",
  "Sports Date",
  "Friends Date",
  "Travel Date",
  "Stay at home Date",
  "Romantic Date",
];

module.exports.places = [
  "Arcade",
  "Aquarium",
  "Hike",
  "Karaoke",
  "Ice Skates",
  "Concert",
  "Zoo",
  "Park",
  "Cafe",
  "Bowling",
  "Bookstore",
  "Dinning",
  "Museum",
  "Library",
  "Picnic",
  "Garden",
  "Carnival",
  "Stargazing",
  "Shopping",
  "Beach",
  "Shelter",
];
